version: '3'

services:

  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - ${BACKEND_PORT}:80


  frontend:
    build: 
      context: ./frontend/food-recommendation
    volumes:
      - ./frontend/food-recommendation:/app/frontend/food-recommendation
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_SERCIVE_NAME=http://backend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    