import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from '../../components/navbar'
import React, { useState,useEffect } from 'react';
import "./globals.css";
import Footer from "../../components/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Recipie Recommendation",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme='cupcake' className="h-screen">
      {/* <ThemeProvider> */}
        {/* <ClientThemeWrapper> */}
          <body className={`${inter.className} flex flex-col justify-between min-h-screen`}>
            <Navbar />
            <div className="flex-1 ml-auto mr-auto mt-0">
              {children}
            </div>
          <Footer/>
          </body>
        {/* </ClientThemeWrapper> */}
      {/* </ThemeProvider> */}
    </html>
  );
}
