import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from '../../components/navbar'
import React, { useState,useEffect } from 'react';
import "./globals.css";
import Footer from "../../components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Recipie Recommendation",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme='cupcake' className="h-screen">
      {/* <ThemeProvider> */}
        {/* <ClientThemeWrapper> */}
          <body className={`${inter.className} flex flex-col h-full w-full`}>
            <Navbar />
            <div className="mx-auto max-w-8xl m-10 md:m-10 text-2xl flex-grow mb-auto flex flex-col">
              {children}
            </div>
            <Footer />
          </body>
        {/* </ClientThemeWrapper> */}
      {/* </ThemeProvider> */}
    </html>
  );
}
