# Frontend dockerfile 

FROM node:20.5.1-bookworm-slim

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

RUN npm install next

COPY . .

ENV BACKEND_FULL_URI=${Vercel_ENV_VAR_1}

EXPOSE 3000

CMD ["npm","run","dev"]

