# Frontend dockerfile 

FROM node:20.5.1-bookworm-slim

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

ENV PORT=3000

EXPOSE 3000

WORKDIR /frontend/food-recommendation

CMD ["npm","run","dev"]

